{
  "apiVersion": 1,
  "datasources": [
    {
      "name": "Prometheus",
      "type": "prometheus",
      "access": "proxy",
      "url": "http://prometheus:9090",
      "isDefault": true,
      "editable": false
    },
    {
      "name": "Elasticsearch",
      "type": "elasticsearch",
      "access": "proxy",
      "url": "http://elasticsearch:9200",
      "database": "[app-logs-]YYYY.MM.DD",
      "jsonData": {
        "interval": "Daily",
        "timeField": "@timestamp",
        "esVersion": "8.0.0"
      },
      "editable": false
    }
  ]
}
